### ISSUE TITLE
A button for just all games

### ISSUE THREAD

**Issue by taro222** [akorb/SteamShutdown#10]
Hey,

Is it possible to add a button, just to shutdown when all downloads are finished?
I have a very very slow internet connection (48 kb/s max) and it takes me like 5-10 minutes daily to setup steamshutdown because every download needs to start and download a bit till steamshutdown regognises that there is an unfinished game. It would be much better if I can configure a windows autostart and automatically tracks all downloads automatically.

**Comment by akorb** [comment]
Yes the button is possible and I actually have a first test version of this running, but I cannot finish it because I don't have the time until the weekend. I hope you can wait until then.

But I don't know whether the autostart makes sense. Are you really sure you want your computer to get shutdown without doing anything by yourself (including starting the application)? I'll finish the implementation of the button first.

**Comment by akorb** [comment]
Implemented in version 1.7.2
