### ISSUE TITLE
Does not Shutdown?

### ISSUE THREAD

**Issue by ibrokemypie** [akorb/SteamShutdown#11]
Left this on overnight while downloading a bunch of games. Put all the games into the right column, and in the morning computer was still running but no games in either column and all downloads had finished...

**Comment by akorb** [comment]
Thanks for you report.
It's difficult for me to reproduce this. What operating system are you running?

**Comment by ibrokemypie** [comment]
Windows 10 anniversary. Latest non-insider

**Comment by akorb** [comment]
Execute this command in the command line: `shutdown /s /t 0`
Be careful, this command will probably shutdown your computer.
Please tell me whether your PC actually shutdown.

**Comment by tofrus** [comment]
idk where to say but thank you for this, its really help me and my friend, or even everyone who needs it :D once again THANK YOU SO MUCH!

**Comment by akorb** [comment]
@tofrus Thank you very much for these kind words. I appreciate that. I am always glad if someone likes and uses my work :) I just uploaded v2 ( https://github.com/akorb/SteamShutdown/releases/latest ) with a new design. Check it out, suggestions for improvements is always welcoming.

@ibrokemypie Because of the redesign many things changed and I still wasn't able to reproduce this issue. If you still have this problem with the latest version (v2), please let me know.
