### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by DreiPixel** [akorb/SteamShutdown#18]
it crashes for me on startup
Windows 10 Build 16299.125
[SteamShutdown_Log.txt](https://github.com/akorb/SteamShutdown/files/1769143/SteamShutdown_Log.txt)
 
i tried to start as adminstrator but that didnt worked

**Comment by akorb** [comment]
Thanks for your report.
Would you please execute the modified attached version and send me the log file once again?
The resulting log file should contain the content of the .acf file from which the crash is caused. You might want to remove the number in the line with `"LastOwner"`, because that's the ID of your steam profile.

[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/1770924/SteamShutdown.zip)

**Comment by DreiPixel** [comment]
[SteamShutdown_Log.txt](https://github.com/akorb/SteamShutdown/files/1770962/SteamShutdown_Log.txt)
here you go

**Comment by akorb** [comment]
Well, that's confusing. Your file `E:\Steam Software\SteamApps\appmanifest_22320.acf` contains the wrong data. It's an INDX file. These files contain information about a NTFS filesystem.
The acf file should usually be about `The Elder Scrolls III: Morrowind® Game of the Year Edition`. If you don't have that game installed, you can delete this acf file.

**Comment by DreiPixel** [comment]
It works now after deleting that file. I have no idea how that file got like that.

**Comment by akorb** [comment]
Maybe repartitioned anytime? Just a guess.

But anyways, I would say the program shouldn't crash just because of one corrupt acf file. I will change that. Thanks for your report.
