### ISSUE TITLE
Windows SmartScreen blocks the app

### ISSUE THREAD

**Issue by Trider12** [akorb/SteamShutdown#46]
# System stats
* Windows 10 21H1 x64
* SteamShutdown 2.3.8
# Description
Windows SmartScreen stops the app from being launched via GUI (even as admin). Launching from cmd/ps is fine
Disabling SmartScreen solves the issue (however, most users aren't even aware of its existence)
I suspect it probably has something to do with the digital signature of the app (or maybe Microsoft needs to add it to their whitelist)

# Edit
It also failed to shutdown PC

**Comment by akorb** [comment]
Hi, does all this still occur with the latest version? (v2.4.0)

**Comment by Ethenski** [comment]
> Hi, does all this still occur with the latest version? (v2.4.0)

Still happens with latest version. I'm on Windows 11

**Comment by akorb** [comment]
I submitted the current version (v2.4.0) for a check that they can validate SteamShutdown is not malware and therefore, disable this notification. Here: https://www.microsoft.com/en-us/wdsi/filesubmission

That's their response:

> The warning you experienced indicates that the application had not established reputation with the Microsoft Defender SmartScreen Application Reputation feature at that time. We can confirm that the application %steamshutdown.exe%(sha256 -6db355a8fd4a4c62d92785b375120e7135e0baa95f48845febe5ac5539ea3e36) has since established reputation and attempting to download or run the application should no longer show any warnings.
Please note, however, that the submitted files are not signed using a valid digital certificate. Unsigned files will have to establish reputation each time a new version is released.
Application Reputation warnings are meant to indicate when applications do not have known positive reputation. This doesn’t mean that the application is malicious, only that it is “unknown.” Users can still proceed to download and run the application. If establishing reputation immediately is critical, you may want to consider investing in an EV Authenticode certificate. A valid EV Authenticode certificate can immediately establish reputation with SmartScreen reputation services even if no prior reputation exists. In order to be considered a valid EV certificate, the certificate must be issued by a Certificate Authority that is authorized by the Microsoft Trusted Root Certificate Program and recognized as an Extended Validation issuer.
Thank you for contacting Microsoft.

So, unfortunately, I can't do something about it. The user has to decide whether it's still fine to execute the program. Over time, SmartScreen will stop warning the users.
As far as I understood, SmartScreen gets updated by the "Microsoft Defender Definition" Updates. Hence, the pop-up should not appear anymore as soon as the definition update declaring v2.4.0 of SteamShutdown as fine software (maybe it even already happened, I don't know). But that's out of my hand
