### ISSUE TITLE
Unselects download and does not perform action

### ISSUE THREAD

**Issue by LeonTheDev-io** [akorb/SteamShutdown#48]
Hey there, when I select a download, it will unselect after changing to 'patched' for example ( I am not sure if that is the cause ), does it even work with updates, or is it only made for actual new downloads?

Regards, Leon
PS: I am running it as admin, yes

**Comment by robbely** [comment]
I've just used the app for the first time and had the same thing happen.

**Comment by akorb** [comment]
It should also work for updates. But since I rely on undocumented meta data information which Valve can change whenever they want, sometimes it breaks. Unfortunately, I have exams at the moment and don't have time to investigate this until the end of February.

For anyone who wants to dig into this, this is the code which checks if a game is getting downloaded:
https://github.com/akorb/SteamShutdown/blob/master/SteamShutdown/App.cs#L17

Also, SteamShutdown does not require any admin priviliges. Therefore, better execute it as a normal user for sake of security.

**Comment by akorb** [comment]
For my understanding, with 'patched' you mean that the update download is finished, right?
And which operating system are you using?

**Comment by LeonTheDev-io** [comment]
Uh, I think so, when it finished the actual downloading, it says patching
and installs at the files into the right folders, I saw someone else making
this possible with steams drive usage.

**Comment by akorb** [comment]
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/8144794/SteamShutdown.zip)
Does this version solve the problem?

**Comment by LeonTheDev-io** [comment]
Sorry for the late reply, it works now, amazing
